version: "3.3"
services:
  
  mysql:
    image: mysql
    ports:
      - "3308:3306"
    volumes:
      - mysqldb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vollmed-db

volumes:
  mysqldb: 
   
      